version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/
permissions:
  - object: /var/www/html
    owner: apache
    group: apache
    mode: 775
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/verify_service.sh
      runas: root
